import { promises as fs } from "fs";
import type { CheckFn } from "../runner";

const REPORT = process.env.GOACCESS_REPORT ?? "/data/goaccess/index.html";

/** GoAccess report is regenerated by cron every 5 min. Stale = cron stuck. */
export const goaccessReportFreshness: CheckFn = async () => {
  try {
    const stat = await fs.stat(REPORT);
    const ageMin = (Date.now() - stat.mtimeMs) / 60_000;
    return {
      id: "goaccess",
      group: "traffic",
      name: "GoAccess report",
      status: ageMin > 60 ? "fail" : ageMin > 15 ? "warn" : "ok",
      detail: `regenerated ${ageMin.toFixed(1)}m ago`,
    };
  } catch {
    return {
      id: "goaccess",
      group: "traffic",
      name: "GoAccess report",
      status: "fail",
      detail: `cannot stat ${REPORT}`,
    };
  }
};
